server:
  port: 8080

security:
  rotate:
    key: ${ROTATE_KEY}
  jwt:
    secret: ${JWT_SECRET}
    issuer: "scrm-api"
    subject: "scrm-technical-client"
    type: "TECH"
    expiration-days: 90

logging:
  level:
    root: INFO
    com.isp.scrm: INFO
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
